### ISSUE TITLE
Reconsider excluding web/.gitignore explicitly

### ISSUE THREAD

**Issue by markfullmer** [pantheon-systems/drupal-project#19]
## Background
In https://github.com/pantheon-systems/drupal-project/commit/2badb369e6e6726d84c0f25adad246cc8756bfed, the `web/.gitignore` file was explicitly excluded from version control. 

However, this file is a legitimate thing for `drupal/core-composer-scaffold` to create, per https://github.com/drupal/core-composer-scaffold#gitignore

This "problem" is a new manifestation because Drupal 9.2.0 switched from using `README.txt` to `README.md`. As the [release notes](https://www.drupal.org/project/drupal/releases/9.2.0) indicate:

> Drupal’s README now focuses on shepherding new contributors into the Drupal ecosystem and uses the Markdown format. The usage information previously contained in the README.txt file has been extracted to a newly created USAGE.txt file in the core directory. **Sites that are using the drupal/core-composer-scaffold plugin to exclude README.txt should update their configuration to exclude README.md instead**

## Analysis/Recommendation
`pantheon-systems/drupal-project` should not exclude `web/.gitignore` in its default `.gitignore`. Instead, either exclude `README.md` it the `composer.json`’s scaffolding directives, or instruct sites/upstreams to do that themselves.

**Comment by greg-1-anderson** [comment]
With `web/.gitignore` ignored, we will have the following behavior:

- `composer install` will write the scaffold files
- For files such as `web/README.md` that are not ignored, drupal/composer-scaffold will write a `web/.gitignore` (or a .gitignore in another, deeper location)
- Because `web/.gitignore` is itself ignored, the creation of this file will not cause the Integrated Composer build to fail.
- Because `web/.gitignore` itself ignores `web/README.md`, the placement of the `web/README.md` file will not cause the Integrated Composer build to fail.
- When the artifacts tag is created, `web/.gitignore` will be added to the tag, as will `web/README.md`, because any .gitignored file that is created by `composer install` is presumed to be part of the build artifacts
- When test/live is deployed, it will be deployed from the artifacts tag, so `web/README.md` & etc. will be part of the deployed build

Adding `web/.gitignore` goes against the original design of Integrated Composer, which was to require sites to be very explicit about where the build artifacts are placed; however, it does not cause any operational problems by being included, at least not as far as I can tell. Has the new behavior caused any problems on any of your sites?

**Comment by markfullmer** [comment]
Thanks for spelling this out clearly, @greg-1-anderson !

> Has the new behavior caused any problems on any of your sites?

No operational problems, no. Excluding `web/.gitignore` successfully prevents _any_ unexpected scaffolding files in the `web` docroot from causing a build failure on Pantheon, and as you point out, any files would still be part of the build artifact. I think I would have expected that you would explicitly add `web/README.md` to the gitignores, alongside the existing ones. Perhaps the approach chosen was trying to anticipate future instances where Drupal core adds a new scaffold file, rather than "keep up" with specific files?

The only "harm" I could see in this approach is wholly and purely theoretical: a site where developers _want_ to use a `.gitignore` in the web root. That said, I can't envision a scenario where a `web/.gitignore` would be **necessary**, since `.gitignore` directives could be added elsewhere.

The main reason for raising this, instead, was because it seemed to _override_ the logic from `core-composer-scaffold` directives to solve the problem, rather than solving the problem through updating `core-composer-scaffold` directives in the `composer.json` file. But since you can't add a wildcard `core-composer-scaffold` directive that ignores _all_ scaffolded files the `webroot`, the "correct" solution means that Integrated Composer sites would have to _do something_ each time a new scaffold file is introduced.

**In sum, I conclude that the current solution is the best, forward-thinking resolution for Pantheon sites using Integrated Composer, and will result in far less frustration for Pantheon customers (and Pantheon support staff!) than the "correct" solution.**

Closing this issue!
